### ISSUE TITLE
[BUG] crash after fresh setup

### ISSUE THREAD

**Issue by dzagu** [K4ryuu/CS2_SimpleRanks#1]
**Describe the bug**
After clean setup I have lag when joining to team

**To Reproduce**
Meta info:
```
meta list
Listing 4 plugins:
  [01] Mini VIP (1.0.0) by Phoenix (˙·٠●Феникс●٠·˙)
  [02] CounterStrikeSharp (0.1.0) by Roflmuffin
  [03] <NOFILE>
  [04] Base Admin (1.2) by Pisex
meta version
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1256
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Oct 26 2023 10:57:52
    Built from: https://github.com/alliedmodders/metamod-source/commit/6ee74f0
    Build ID: 1256:6ee74f0
    http://www.metamodsource.net/
```

1. Fresh install
2. Setup db, nothing more
3. join team
4. type !rank

**Expected behavior**

**Media (Optional)**
If applicable, add screenshots or videos to help explain your problem.

**Logs (Optional)**
```
SV:  Disconnect client 'DZAGU GLOBALELITE.pl' from server(5): NETWORK_DISCONNECT_OVERFLOW
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.
[#784628046 UDP steamid:76561198008982573@192.168.31.1:59274] recv queue overflow 1000 messages already queued.

```
**Additional context (Optional)**

**Comment by dzagu** [comment]
Whole log
```
Error: Error while removing points: Connect Timeout expired.
NetChan DZAGU GLOBALELITE.pl ProcessMessages has taken more than 15042ms to process 1060 messages.  (Current message type: 'NetMessagePacketStart [-1]')
netchan.cpp (1366) : Assertion Failed in function ProcessMessages():
false
Disconnecting netchan because of excessive CPU usage /+/ 15042ms, 1060, current message type: 'NetMessagePacketStart [-1]'
SV:  Disconnect client 'DZAGU GLOBALELITE.pl' from server(5): NETWORK_DISCONNECT_OVERFLOW
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] recv queue overflow 1000 messages already queued.
Error: Error while removing points: Connect Timeout expired.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'PointsForBots' was not present in the dictionary.
   at K4ryuuSimpleRanks.SimpleRanks.<SetupGameEvents>b__9_9(EventPlayerDeath event, GameEventInfo info) in /Users/sples/Documents/GitHub/CS2_SimpleRanks/src/K4ryuuSimpleRanks.cs:line 259
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 70
Client 0 'DZAGU GLOBALELITE.pl' signon state SIGNONSTATE_FULL -> SIGNONSTATE_NONE
Server is hibernating
ResetGameConVarsToDefaults
SV:  Dropped client 'DZAGU GLOBALELITE.pl' from server(5): NETWORK_DISCONNECT_OVERFLOW
CloseSteamNetConnection handle #2636378801 (userdata 0)
Disassociating NetChan DZAGU GLOBAL                      [-1] (unknown) from Steam Net Connection handle #2636378801 (userdata 0)
Summary of connection [#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898]:
    End-to-end connection: connected
        Current rates:
            Sent:  68.0 pkts/sec   2.0 K/sec
            Recv: 171.5 pkts/sec  37.7 K/sec
            Ping:0ms    Max latency variance: ???ms
            Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
            Est avail bandwidth: 768.0KB/s
            Bytes buffered: 0
        Lifetime stats:
            Totals
                Sent:      1,174 pkts          76,400 bytes
                Recv:      4,341 pkts       1,427,667 bytes
                Recv w seq:      4,340 pkts
                Dropped   :          0 pkts   0.00%
                OutOfOrder:          0 pkts   0.00%
                OOOFixed  :          0 pkts   0.00%
                Duplicate :          0 pkts   0.00%
                SeqLurch  :          0 pkts   0.00%
            Ping histogram: (1140 total samples)
                     0-25    25-50    50-75   75-100  100-125  125-150  150-200  200-300     300+
                     1140        0        0        0        0        0        0        0        0
                   100.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%     0.0%
            Ping distribution:
                5th   50th   75th   95th   98th
                0ms    0ms    0ms    0ms    0ms
            Connection quality histogram: (9 measurement intervals)
                perfect    99+  97-99  95-97  90-95  75-90  50-75    <50   dead
                      9      0      0      0      0      0      0      0      0
                 100.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%   0.0%
            Connection quality distribution:
              50th  25th
              100%  100%
            Latency variance histogram not available
        Rate stats received from remote host 0.0s ago:
            Sent: 186.3 pkts/sec  38.1 K/sec
            Recv:  68.5 pkts/sec   2.0 K/sec
            Ping:0ms    Max latency variance: ???ms
            Quality:  100%  (Dropped:0.00%  WeirdSeq:0.00%)
            Bytes buffered: 0
        No lifetime stats received from remote host

[#2636378801 UDP steamid:76561198008982573@192.168.31.1:59898] closed by app, linger requested but not needed (2005) NETWORK_DISCONNECT_OVERFLOW
Removing Steam Net Connection for 192.168.31.1:59898, handle #2636378801

```

**Comment by K4ryuu** [comment]
Thank you for the feedback!

The crash has been fixed with [this](https://github.com/K4ryuu/CS2_SimpleRanks/commit/eac45d1f6344a5540c469aff9c11d7774cbf0b8f) commit and also there is an error for Connect Timeout expired because of wrong db details given.
