### ISSUE TITLE
Crash server !ranktop

### ISSUE THREAD

**Issue by yabaldeu** [K4ryuu/CS2_SimpleRanks#7]
server crashes if write !ranktop

**Comment by K4ryuu** [comment]
Greetings,
Do you have any dump or log about the crashes?

**Comment by yabaldeu** [comment]
Nothing in the plugin logs, that's what he writes in the console after entering the command:

Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at K4ryuuSimpleRanks.Queries.GetTopPlayersAsync() in /Users/sples/Documents/GitHub/CS2_SimpleRanks/src/Queries.cs:line 91
   at K4ryuuSimpleRanks.SimpleRanks.OnCommandCheckRankTop(CCSPlayerController player, CommandInfo command) in /Users/sples/Documents/GitHub/CS2_SimpleRanks/src/K4ryuuSimpleRanks.cs:line 480
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
./game/cs2.sh: line 118:    40 Aborted                 (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 134
[Pterodactyl Daemon]: Out of memory: false

debug or log crashes l don't know where gеt it :(

**Comment by K4ryuu** [comment]
The crash has been fixed with the https://github.com/K4ryuu/CS2_SimpleRanks/commit/7bc7fe4f2f2da60a546f103cd4aa42de8de64dfd commit.
Thank you for the feedback!
